### ISSUE TITLE
workshop header

### ISSUE THREAD

**Issue by Sramos9191** [geekwise-alonzo-yrigollen/geekwise-wordpress#10]
- the navigation links need to fit on one line
- the "Fast no fluff" line & logo need to line up with the "Professional Geek Series"

**Comment by geekwise-alonzo-yrigollen** [comment]
#10 almost still need to raise the geekwise logo element

**Comment by geekwise-alonzo-yrigollen** [comment]
@Sramos9191 update; will begin here tomorrow 5/28/2016

**Comment by geekwise-alonzo-yrigollen** [comment]
got it...gonna switch over to madera. tired of looking at geekwise code. Hip hop back in forth works better for me, if that is okay with you???

**Comment by Sramos9191** [comment]
Yeah, since it is already so close to lunch just work on Madera for the remainder of the class. I’ll send you over the image for the main page

**Comment by geekwise-alonzo-yrigollen** [comment]
you got it....
