### ISSUE TITLE
team header logo

### ISSUE THREAD

**Issue by Sramos9191** [geekwise-alonzo-yrigollen/geekwise-wordpress#16]
the logo needs to be brought down so that its lined up with the navigation

**Comment by geekwise-alonzo-yrigollen** [comment]
logo resolved #16 issue complete @Sramos9191

**Comment by Sramos9191** [comment]
@geekwise-alonzo-yrigollen this is still not complete

**Comment by geekwise-alonzo-yrigollen** [comment]
@Sramos9191 this is issue 16 for this morning 6/1/2016
