### ISSUE TITLE
about content styling issues

### ISSUE THREAD

**Issue by Sramos9191** [geekwise-alonzo-yrigollen/geekwise-wordpress#18]
do you have line-height on your paragraphs? there is a lot of space between the lines.

![screen shot 2016-05-26 at 10 13 54 am](https://cloud.githubusercontent.com/assets/7436666/15583463/bb2620dc-232a-11e6-934f-3f9534a4bfe9.png)

**Comment by geekwise-alonzo-yrigollen** [comment]
got it
