### ISSUE TITLE
course - STEM button

### ISSUE THREAD

**Issue by Sramos9191** [geekwise-alonzo-yrigollen/geekwise-wordpress#24]
add the STEM course button across the top

![screen shot 2016-06-07 at 10 56 48 am](https://cloud.githubusercontent.com/assets/7436666/15868893/93bcaae8-2c9e-11e6-9121-ddb8315a1e5e.png)

**Comment by geekwise-alonzo-yrigollen** [comment]
@Sramos9191 6/10/2016 working on this one this morning...
