### ISSUE TITLE
course - paragraph alignment

### ISSUE THREAD

**Issue by Sramos9191** [geekwise-alonzo-yrigollen/geekwise-wordpress#25]
left align the paragraph above the courses table

![screen shot 2016-06-07 at 10 57 37 am](https://cloud.githubusercontent.com/assets/7436666/15868913/b1101e36-2c9e-11e6-9949-8f8815acd20e.png)

**Comment by geekwise-alonzo-yrigollen** [comment]
did this one...my schedule is off today; gotta do a lot of prep work for decipher just to let you know.
