### ISSUE TITLE
global font issue

### ISSUE THREAD

**Issue by Sramos9191** [geekwise-alonzo-yrigollen/geekwise-wordpress#4]
sent the documents for implementing the fonts on your website

**Comment by Sramos9191** [comment]
@geekwise-alonzo-yrigollen please work on this **5/26/16** morning from 8am - 10am

**Comment by geekwise-alonzo-yrigollen** [comment]
working on this issue this morning #4 @Sramos9191 6/2/2016

**Comment by geekwise-alonzo-yrigollen** [comment]
@Sramos9191 6/3/2016 whoohooo!! was able to get Lato font to work...currently going to through pages applied font. Next will be the ciria one to specified one.

**Comment by Sramos9191** [comment]
@geekwise-alonzo-yrigollen looking good!
