### ISSUE TITLE
about page content

### ISSUE THREAD

**Issue by Sramos9191** [geekwise-alonzo-yrigollen/geekwise-wordpress#7]
the font size needs to be smaller

**Comment by geekwise-alonzo-yrigollen** [comment]
@Sramos9191 priority for the morning 5/25/16

**Comment by Sramos9191** [comment]
@geekwise-alonzo-yrigollen the font size still needs to be smaller

![screen shot 2016-05-25 at 3 43 37 pm](https://cloud.githubusercontent.com/assets/7436666/15558532/7e1f526c-228f-11e6-8b32-38b568812e58.png)

**Comment by geekwise-alonzo-yrigollen** [comment]
font size - resolved
